#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 0
param set-default COM_OBL_RC_ACT 5
param set-default COM_OF_LOSS_T 1.0
param set-default COM_FAIL_ACT_T 0.5

param set-default MPC_TKO_SPEED 5.0
param set-default MPC_TKO_RAMP_T 0.3
param set-default MPC_LAND_SPEED 1.5
param set-default MPC_LAND_ALT1 3.0
param set-default MPC_LAND_ALT2 1.0
param set-default MPC_Z_VEL_MAX_UP 6.0
param set-default MPC_Z_VEL_MAX_DN 3.0
param set-default MPC_XY_VEL_MAX 15.0

# Disable magnetic interference check (needed for multi-drone SITL)
param set-default COM_ARM_MAG_STR 0
param set-default EKF2_MAG_CHECK 0
